### ISSUE TITLE
Failure to Start

### ISSUE THREAD

**Issue by dasmoover** [bugaiov/capwatch#2]
/var/lib/gems/2.3.0/gems/capwatch-0.2.4/lib/capwatch/fund.rb:20:in `value_btc': undefined method `sum' for #<Array:0x00000001fe40d8> (NoMethodError)
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/lib/capwatch/fund.rb:63:in `block in distribution'
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/lib/capwatch/fund.rb:62:in `each'
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/lib/capwatch/fund.rb:62:in `distribution'
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/lib/capwatch/fund.rb:46:in `build'
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/lib/capwatch/fund.rb:12:in `initialize'
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/exe/capwatch:21:in `new'
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/exe/capwatch:21:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/exe/capwatch:18:in `loop'
        from /var/lib/gems/2.3.0/gems/capwatch-0.2.4/exe/capwatch:18:in `<top (required)>'
        from /usr/local/bin/capwatch:23:in `load'
        from /usr/local/bin/capwatch:23:in `<main>'

**Comment by bugaiov** [comment]
@dasmoover looks like you're using an old ruby version which is lower than `2.4`. 

(method `#sum` was introduced in 2.4+ version.)

When I developed this program, I did not consider older ruby versions.

 I think the easiest solution would be to upgrade your ruby version to the latest. `2.4.2p198` would be sufficient. Good luck!!
