### ISSUE TITLE
Release-notes template for the next release:

### ISSUE THREAD

**Issue by berkes** [bugaiov/capwatch#6]
In case a new release is wanted, I've prepared some bullets for the release-notes. 

* Allow defining a Fiat currency to monitor prices in, not just USD.
* Introduce support for [anybar](https://github.com/tonsky/AnyBar).
* Add a watch feature: toggle auto-redrawing on and off.
* Fix to show sub-top-200 coins as well, previously causing a `NoCoinInProvider` exception.

**Comment by bugaiov** [comment]
Thank you! will use it! https://github.com/bugaiov/capwatch/releases/tag/v2.5.6 @berkes
